sudo: required
dist: trusty

#install google chrome, using addons
addons:
  chrome: stable

language: node_js
node_js:
  - "8.9"

before_script:
  - npm install --quiet -g gulp-cli

script:
- gulp build
- npm run setup:demo
- gulp test:demo_ci

after_success: gulp coveralls
