sudo: required
dist: trusty

#install google chrome, using addons
addons:
  chrome: stable

language: node_js
node_js:
  - "8.7"

before_script:
  - npm install --quiet -g gulp-cli

script: gulp test:ci

after_success: gulp coveralls
